#!/bin/bash
echo "Будет установлен Vless с транспортом XHTTP"
sleep 3
apt update
apt install qrencode curl jq -y

# Включаем bbr
bbr=$(sysctl -a | grep net.ipv4.tcp_congestion_control)
if [ "$bbr" = "net.ipv4.tcp_congestion_control = bbr" ]; then
echo "bbr уже включен"
else
echo "net.core.default_qdisc=fq" >> /etc/sysctl.conf
echo "net.ipv4.tcp_congestion_control=bbr" >> /etc/sysctl.conf
sysctl -p
echo "bbr включен"
fi

# Xray-core install
bash -c "$(curl -4 -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ install
[ -f /usr/local/etc/xray/.keys ] && rm /usr/local/etc/xray/.keys
touch /usr/local/etc/xray/.keys
echo "shortsid: $(openssl rand -hex 8)" >> /usr/local/etc/xray/.keys
echo "uuid: $(xray uuid)" >> /usr/local/etc/xray/.keys
xray x25519 >> /usr/local/etc/xray/.keys

export uuid=$(cat /usr/local/etc/xray/.keys | awk -F': ' '/uuid/ {print $2}')
export privatkey=$(cat /usr/local/etc/xray/.keys | awk -F': ' '/PrivateKey/ {print $2}')
export shortsid=$(cat /usr/local/etc/xray/.keys | awk -F': ' '/shortsid/ {print $2}')

# Генерация пароля для Shadowsocks
ss_password=$(openssl rand -base64 32)

# Create config file
touch /usr/local/etc/xray/config.json
cat << EOF > /usr/local/etc/xray/config.json
{
  "log": {
    "loglevel": "warning"
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "domain": [
          "geosite:category-ads-all"
        ],
        "outboundTag": "block"
      },
      {
        "type": "field",
        "ip": [
          "geoip:cn"
        ],
        "outboundTag": "block"
      }
    ]
  },
  "inbounds": [
    {
      "listen": "0.0.0.0",
      "port": 443,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "$uuid",
            "flow": ""
          }
        ],
        "decryption": "none"
      },
      "streamSettings": {
        "network": "xhttp",
        "xhttpSettings": {
          "path": "/",
          "mode": "auto"
        },
        "security": "reality",
        "realitySettings": {
          "show": false,
          "dest": "www.tbank.ru:443",
          "serverNames": [
            "www.tbank.ru"
          ],
          "privateKey": "$privatkey",
          "minClientVer": "",
          "maxClientVer": "",
          "maxTimeDiff": 0,
          "shortIds": [
            "$shortsid"
          ],
          "spiderX": "/",
          "fingerprint": "chrome"
        }
      },
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls",
          "quic",
          "fakedns"
        ],
        "metadataOnly": false,
        "routeOnly": false
      }
    },
    {
      "listen": "0.0.0.0",
      "port": 8080,
      "protocol": "shadowsocks",
      "settings": {
        "method": "2022-blake3-aes-256-gcm",
        "password": "$ss_password",
        "network": "tcp,udp"
      },
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls",
          "quic",
          "fakedns"
        ],
        "metadataOnly": false,
        "routeOnly": false
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "tag": "block"
    }
  ]
}
EOF

# Исполняемый файл для ссылки основного пользователя
touch /usr/local/bin/link
cat << 'EOF' > /usr/local/bin/link
#!/bin/bash
# Сбор актуальных данных
port_vless=$(jq -r '.inbounds[0].port' /usr/local/etc/xray/config.json)
uuid=$(jq -r '.inbounds[0].settings.clients[0].id' /usr/local/etc/xray/config.json)
mode=$(jq -r '.inbounds[0].streamSettings.xhttpSettings.mode' /usr/local/etc/xray/config.json)
sni=$(jq -r '.inbounds[0].streamSettings.realitySettings.serverNames[0]' /usr/local/etc/xray/config.json)
pbk=$(cat /usr/local/etc/xray/.keys | awk -F': ' '/Password/ {print $2}')
sid=$(cat /usr/local/etc/xray/.keys | awk -F': ' '/shortsid/ {print $2}')
fp=$(jq -r '.inbounds[0].streamSettings.realitySettings.fingerprint' /usr/local/etc/xray/config.json)
ip=$(timeout 3 curl -4 -s icanhazip.com)
port_ss=$(jq -r '.inbounds[1].port' /usr/local/etc/xray/config.json)
pass=$(jq -r '.inbounds[1].settings.password' /usr/local/etc/xray/config.json)
method=$(jq -r '.inbounds[1].settings.method' /usr/local/etc/xray/config.json)
userinfo_base64=$(echo -n "$method:$pass" | base64 -w0)

# Сборка конфигов vless и ss для вывода
vless_link="vless://$uuid@$ip:$port_vless?security=reality&path=%2F&host=&mode=$mode&sni=$sni&fp=$fp&pbk=$pbk&sid=$sid&spx=%2F&type=xhttp&encryption=none#💉 VLESS-XHTTP"
ss_link="ss://$userinfo_base64@$ip:$port_ss#📐 Shadowsocks-2022"

# Вывод итоговых данных
echo -e "\e[1;32mСсылки для подключения:\e[0m"
echo -e "\n\e[1;34m[+] VLESS XHTTP REALITY:\e[0m"
echo -e "\e[36m$vless_link\e[0m"

echo -e "\n\e[1;34m[+] SHADOWSOCKS 2022:\e[0m"
echo -e "\e[36m$ss_link\e[0m"

echo -e "\n\e[1;33m==================================================\e[0m"
echo "QR-код для VLESS:"
echo "$vless_link" | qrencode -t ansiutf8
echo -e "\e[1;33m==========================================================================\e[0m"
echo "QR-код для Shadowsocks:"
echo "$ss_link" | qrencode -t ansiutf8
echo -e "\e[1;33m==========================================================================\e[0m"

EOF
chmod +x /usr/local/bin/link

systemctl restart xray

# Autoupdate-check
(crontab -l 2>/dev/null; echo "0 4 */5 * * bash -c \"\$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)\" @ install > /dev/null 2>&1 # Xray-update") | crontab -

echo -e "\n\e[1;33m==================================================\e[0m"
echo -e "\e[1;32m      XRAY INSTALLATION COMPLETE 🎭\e[0m"
echo -e "\e[1;33m==================================================\e[0m"
link
